//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductMaster.DataAccess.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int IdProduct { get; set; }
        public string NameProduct { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string Email { get; set; }
        public int IdCountry { get; set; }
        public string Cost { get; set; }
        public string UnitsAvailable { get; set; }
        public string SoldUnits { get; set; }
        public bool StateProduct { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
